#!/bin/bash
# llama-server startup script for MeDocPro
# Auto-generated by install-llamacpp-binary.py

LLAMA_SERVER="/mnt/c/Users/admin/Desktop/MeDocPro/llama.cpp/build/bin/llama-server"
MODELS_DIR="/mnt/c/Users/admin/Desktop/MeDocPro/models"
PORT=8080
HOST="127.0.0.1"
MODEL_PATH="$MODELS_DIR/mistral-7b-instruct-v0.3.Q4_K_M.gguf"

# Check if model exists
if [ ! -f "$MODEL_PATH" ]; then
    echo "❌ Model not found: $MODEL_PATH"
    echo "📋 Run: python3 scripts/download-models.py recommended"
    exit 1
fi

echo "🚀 Starting llama-server..."
echo "📍 Model: $MODEL_PATH"
echo "🌐 Server: http://$HOST:$PORT"

# Start llama-server
"$LLAMA_SERVER" \
    --model "$MODEL_PATH" \
    --host "$HOST" \
    --port $PORT \
    --ctx-size 4096 \
    --n-predict 512 \
    --threads 4 \
    --batch-size 512 \
    --verbose